export const gastosPosicion5 = 0.75
export const gastosPosicion6 = 1.25
export const gastosPosicion7 = 1.75
export const gastosPosicion8 = 2.25
export const mensaje1 = 'ERES LÍDER! Como sigas así te vas a llevar una cena gratis y lo mejor de todo... EL TROFEO!'
export const mensaje2 = 'Quieres ese trofeo? Pues a por todas!! Échale ganas y colócate en primera posición!'
export const mensaje3 = 'No te rindas! Vas tercero, no tienes lejos ganar y poder beber cerveza desde el trofeo!'
export const mensaje4 = 'Mitad de tabla, no está mal pero un par de fichajes no te vendrían mal.'
export const mensaje5 = 'Sal de aqui!! Pagas poco semanalmente pero con un poco más de esfuerzo consigues no pagar!!'
export const mensaje6 = 'Hay algunos peor que tu pero no estás para muchas celebraciones... Si te descuidas te va a tocar pagar hasta el pan!'
export const mensaje7 = 'Mejora un poco campeón que vas a pagar la cena tu solo!'
export const mensaje8 = 'Dios santo de mi vida... Si no jugaras no habría diferencias con lo que estás haciendo.'